services:
  app:
    build:
      context: .
    ports:
      - "8080:8080"
    volumes:
      - app_data:/app/data/
    env_file: .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 2m30s
      timeout: 10s
      retries: 3
      start_period: 40s
      start_interval: 5s

volumes:
  app_data:
